version: "3.7"
services:
  app:
    image: docker.io/library/thinkquest
    restart: unless-stopped
    volumes:
      - ./:/var/www
     #- ./storage/app/public:/var/www/storage/app/public
      # - ./php:/usr/local/etc/php/conf.d
        #- ./bootstrap/cache:/var/www/bootstrap/cache
      # - ./storage/app:/var/www/storage/app
      # - ./imagick:/etc/ImageMagick-6
    # networks:
    #   - public_net
    env_file:
      - .env
    ports:
      - 8000:8000

  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   ports:
  #     - 8001:80
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.confe
  #   networks:
#   #     - public_net

# networks:
#   public_net:
#     external: true
