version: "3.7"
services:
  app:
    image: elearning
    restart: unless-stopped
    volumes:
      - ./:/var/www
     #- ./storage/app/public:/var/www/storage/app/public
      - ./php:/usr/local/etc/php/conf.d
        #- ./bootstrap/cache:/var/www/bootstrap/cache
        #- ./storage:/var/www/storage
      - ./imagick:/etc/ImageMagick-6
    networks:
      - public_net
    # env_file:
    #   - .env

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public_net

networks:
  public_net:
    external: true
